"""empty message

Revision ID: f4346468b88a
Revises: 
Create Date: 2018-02-27 20:09:51.469806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4346468b88a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('track_name', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_country'), 'calendar', ['country'], unique=False)
    op.create_index(op.f('ix_calendar_end_date'), 'calendar', ['end_date'], unique=False)
    op.create_index(op.f('ix_calendar_start_date'), 'calendar', ['start_date'], unique=False)
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('raceNum', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=64), nullable=True),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_driver')
    op.drop_table('team')
    op.drop_table('driver')
    op.drop_index(op.f('ix_calendar_start_date'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_end_date'), table_name='calendar')
    op.drop_index(op.f('ix_calendar_country'), table_name='calendar')
    op.drop_table('calendar')
    # ### end Alembic commands ###
